### PR TITLE
CSS Flexbox - Michael Van Doorn

### PR DESCRIPTION
**Pull request by Michaelvxd**
CleanShot 2022-12-13 at 20 43 51
CleanShot 2022-12-13 at 20 43 33
CleanShot 2022-12-13 at 20 43 18
CleanShot 2022-12-13 at 20 41 55

What is the default flex-direction of a flex container?
-- row (left to right in ltr; right to left in rtl)
What is the default flex-wrap of a flex container?
-- nowrap (all flex items will be on one line)

### CODE REVIEW

**Comment by Michaelvxd** [comment]
For the **display: flex**, **flex-wrap**, and **justify-content** exercises the instructions note:
 "Give the card deck and each pokemon card some padding to add some whitespace around each card." 

How would adding padding to the card-deck add whitespace between cards?

**Comment by kurtyazdizadeh** [comment]
Good question, I think what the instructions are trying to say is "Give the card deck and each `card wrapper` some padding..."

I can see how that is misleading, adding padding to the wrapper will add space around the pokemon card, since the pokemon card is the content within the `card wrapper`

**Review by kurtyazdizadeh — APPROVED** [review]
Approved!

**Comment by Michaelvxd** [comment]
Ah that makes sense, thank you!

**Pull request merged**
